namespace MachineControlBase
{
    /// <summary>
    /// 시스템 상태 정의
    /// </summary>
    public enum eMachineState
    {
        INIT = 0,
        READY,
        RUN,
        MANUALRUN,
        ALARM,
        ERROR,
    }

    /// <summary>
    /// 프로그램 언어
    /// </summary>
    public enum eLanguage
    {
        KOREAN = 0,
        ENGLISH,
        CHINESE,
    }

    /// <summary>
    /// 사용자 레벨 정의
    /// </summary>
    public enum eUserLevel
    {
        OPERATOR = 0,
        ENGINEER,
        ADMINISTRATOR,
    }

    /// <summary>
    /// 로그 종류 정의
    /// </summary>
    public enum eLogType
    {
        PROGRAM = 0,
        SEQ_MAIN,
        Seq00_Front_MPC,
        Seq01_Rear_MPC_Left,
        Seq02_Rear_MPC_Right,
        Seq03_HolderS_R,
        Seq04_Hopper,
        Seq05_PipePnP,
        Seq06_NeedlePnP,
        Seq07_Transfer,
        Seq08_PipeMount,
        Seq09_NeedleMount,
        Seq10_Dispensing,

        VisionShoot,
        CAM0_PipeNeedlePickUp,
        CAM1_PipePosture,
        CAM2_NeedlePosture,
        CAM3_PipeMount,
        CAM4_NeedleMount,
        CAM5_Dispenser,

        VisionLight,
        AIM_Feeder,
        UV_Control,
    }

    /// <summary>
    /// 아날로그 입력 정의
    /// </summary>
    public enum eAnalogInput
    {
        CH1_REF = 0,
    }

    /// <summary>
    /// 경광등 색상 플래그
    /// </summary>
    public enum _eLightColor
    {
        RED,
        GREEN,
        YELLOW,
        BLACK,
    }

    /// <summary>
    /// 시퀀스 라인 정의
    /// </summary>
    public enum eLine
    {
        Left = 0,
        Right,
    }

    /// <summary>
    /// 니들 핀 작업 상태 정의
    /// </summary>
    public enum eNeedlePinStatus
    {
        Firstwork = 0,
        Secondwork,
        Notwork,
    }

    #region Vision 관련 선언

    /// <summary>
    /// 카메라 이름 및 번호 정의
    /// </summary>
    public enum eCAM : int
    {
        CAM0_PipeNeedlePickUp = 0,
        CAM1_Pipe,
        CAM2_Needle,
        CAM3_PipeMount,
        CAM4_NeedleMount,
        CAM5_Dispenser,
    }

    /// <summary>
    /// Vision VPP 이름 정의
    /// </summary>
    public enum eVppName
    {
        AcqFifo = 0,
        ImageFile,
        ToolBlock,
    }

    /// <summary>
    /// 이미지 회전 정의
    /// </summary>
    public enum eRotate
    {
        _90Deg = 0,
        _180Deg,
        _270Deg,
    }

    #endregion Vision 관련 선언

    /// <summary>
    /// 에러 번호 정의
    /// </summary>
    public enum eErrorCode
    {
        MOTOR0_ERROR = 0,
        MOTOR1_ERROR = 1,
        MOTOR2_ERROR = 2,
        MOTOR3_ERROR = 3,
        MOTOR4_ERROR = 4,
        MOTOR5_ERROR = 5,
        MOTOR6_ERROR = 6,
        MOTOR7_ERROR = 7,
        MOTOR8_ERROR = 8,
        MOTOR9_ERROR = 9,
        MOTOR10_ERROR = 10,
        MOTOR11_ERROR = 11,
        MOTOR12_ERROR = 12,
        MOTOR13_ERROR = 13,
        MOTOR14_ERROR = 14,
        MOTOR15_ERROR = 15,
        MOTOR16_ERROR = 16,
        MOTOR17_ERROR = 17,
        MOTOR18_ERROR = 18,
        MOTOR19_ERROR = 19,
        MOTOR20_ERROR = 20,
        MOTOR21_ERROR = 21,
        MOTOR22_ERROR = 22,
        MOTOR23_ERROR = 23,
        MOTOR24_ERROR = 24,
        MOTOR25_ERROR = 25,
        MOTOR26_ERROR = 26,
        MOTOR27_ERROR = 27,
        MOTOR28_ERROR = 28,
        MOTOR29_ERROR = 29,
        MOTOR30_ERROR = 30,
        MOTOR31_ERROR = 31,
        MOTOR32_ERROR = 32,
        MOTOR33_ERROR = 33,
        MOTOR34_ERROR = 34,
        MOTOR35_ERROR = 35,
        MOTOR36_ERROR = 36,
        MOTOR37_ERROR = 37,
        MOTOR38_ERROR = 38,
        MOTOR39_ERROR = 39,
        MOTOR40_ERROR = 40,
        MOTOR41_ERROR = 41,
        MOTOR42_ERROR = 42,
        MOTOR43_ERROR = 43,
        MOTOR44_ERROR = 44,
        MOTOR45_ERROR = 45,
        MOTOR46_ERROR = 46,
        MOTOR47_ERROR = 47,
        MOTOR48_ERROR = 48,
        MOTOR49_ERROR = 49,
        MOTOR50_ERROR = 50,
        MOTOR51_ERROR = 51,
        MOTOR52_ERROR = 52,
        MOTOR53_ERROR = 53,
        MOTOR54_ERROR = 54,
        MOTOR55_ERROR = 55,
        MOTOR56_ERROR = 56,
        MOTOR57_ERROR = 57,
        MOTOR58_ERROR = 58,
        MOTOR59_ERROR = 59,
        MOTOR60_ERROR = 60,
        MOTOR61_ERROR = 61,
        MOTOR62_ERROR = 62,
        MOTOR63_ERROR = 63,
        MOTOR64_ERROR = 64,
        MOTOR65_ERROR = 65,
        MOTOR66_ERROR = 66,
        MOTOR67_ERROR = 67,
        MOTOR68_ERROR = 68,
        MOTOR69_ERROR = 69,

        MOTOR0_MOVE_TIMEOUT = 100,
        MOTOR1_MOVE_TIMEOUT = 101,
        MOTOR2_MOVE_TIMEOUT = 102,
        MOTOR3_MOVE_TIMEOUT = 103,
        MOTOR4_MOVE_TIMEOUT = 104,
        MOTOR5_MOVE_TIMEOUT = 105,
        MOTOR6_MOVE_TIMEOUT = 106,
        MOTOR7_MOVE_TIMEOUT = 107,
        MOTOR8_MOVE_TIMEOUT = 108,
        MOTOR9_MOVE_TIMEOUT = 109,
        MOTOR10_MOVE_TIMEOUT = 110,
        MOTOR11_MOVE_TIMEOUT = 111,
        MOTOR12_MOVE_TIMEOUT = 112,
        MOTOR13_MOVE_TIMEOUT = 113,
        MOTOR14_MOVE_TIMEOUT = 114,
        MOTOR15_MOVE_TIMEOUT = 115,
        MOTOR16_MOVE_TIMEOUT = 116,
        MOTOR17_MOVE_TIMEOUT = 117,
        MOTOR18_MOVE_TIMEOUT = 118,
        MOTOR19_MOVE_TIMEOUT = 119,
        MOTOR20_MOVE_TIMEOUT = 120,
        MOTOR21_MOVE_TIMEOUT = 121,
        MOTOR22_MOVE_TIMEOUT = 122,
        MOTOR23_MOVE_TIMEOUT = 123,
        MOTOR24_MOVE_TIMEOUT = 124,
        MOTOR25_MOVE_TIMEOUT = 125,
        MOTOR26_MOVE_TIMEOUT = 126,
        MOTOR27_MOVE_TIMEOUT = 127,
        MOTOR28_MOVE_TIMEOUT = 128,
        MOTOR29_MOVE_TIMEOUT = 129,
        MOTOR30_MOVE_TIMEOUT = 130,
        MOTOR31_MOVE_TIMEOUT = 131,
        MOTOR32_MOVE_TIMEOUT = 132,
        MOTOR33_MOVE_TIMEOUT = 133,
        MOTOR34_MOVE_TIMEOUT = 134,
        MOTOR35_MOVE_TIMEOUT = 135,
        MOTOR36_MOVE_TIMEOUT = 136,
        MOTOR37_MOVE_TIMEOUT = 137,
        MOTOR38_MOVE_TIMEOUT = 138,
        MOTOR39_MOVE_TIMEOUT = 139,
        MOTOR40_MOVE_TIMEOUT = 140,
        MOTOR41_MOVE_TIMEOUT = 141,
        MOTOR42_MOVE_TIMEOUT = 142,
        MOTOR43_MOVE_TIMEOUT = 143,
        MOTOR44_MOVE_TIMEOUT = 144,
        MOTOR45_MOVE_TIMEOUT = 145,
        MOTOR46_MOVE_TIMEOUT = 146,
        MOTOR47_MOVE_TIMEOUT = 147,
        MOTOR48_MOVE_TIMEOUT = 148,
        MOTOR49_MOVE_TIMEOUT = 149,
        MOTOR50_MOVE_TIMEOUT = 150,
        MOTOR51_MOVE_TIMEOUT = 151,
        MOTOR52_MOVE_TIMEOUT = 152,
        MOTOR53_MOVE_TIMEOUT = 153,
        MOTOR54_MOVE_TIMEOUT = 154,
        MOTOR55_MOVE_TIMEOUT = 155,
        MOTOR56_MOVE_TIMEOUT = 156,
        MOTOR57_MOVE_TIMEOUT = 157,
        MOTOR58_MOVE_TIMEOUT = 158,
        MOTOR59_MOVE_TIMEOUT = 159,
        MOTOR60_MOVE_TIMEOUT = 160,
        MOTOR61_MOVE_TIMEOUT = 161,
        MOTOR62_MOVE_TIMEOUT = 162,
        MOTOR63_MOVE_TIMEOUT = 163,
        MOTOR64_MOVE_TIMEOUT = 164,
        MOTOR65_MOVE_TIMEOUT = 165,
        MOTOR66_MOVE_TIMEOUT = 166,
        MOTOR67_MOVE_TIMEOUT = 167,
        MOTOR68_MOVE_TIMEOUT = 168,
        MOTOR69_MOVE_TIMEOUT = 169,

        VISION_CLIENT_NOT_CONNECT = 290,
        LASER1_CLIENT_NOT_CONNECT = 291,
        EZI_IO_NOTCONNECT = 296,
        UZ_IO_NOTCONNECT = 297,
        UNI_CONTROLLER_NOTCONNECT = 298,
        CONTROLLER_ERROR = 299,

        MC_POWER_OFF = 300,
        EMG_BUTTON_INPUT = 301,
        MC_AIR_OFF = 302,

        SEQ00_TIME_OUT = 400,
        SEQ01_TIME_OUT = 401,
        SEQ02_TIME_OUT = 402,
        SEQ03_TIME_OUT = 403,
        SEQ04_TIME_OUT = 404,
        SEQ05_TIME_OUT = 405,
        SEQ06_TIME_OUT = 406,
        SEQ07_TIME_OUT = 407,
        SEQ08_TIME_OUT = 408,
        SEQ09_TIME_OUT = 409,
        SEQ10_TIME_OUT = 410,

        MPC_LEFT_RAIL_Y_NOT_FRONT_POSITION = 450,
        MPC_LEFT_RAIL_Y_NOT_REAR_POSITION = 451,
        MPC_RIGHT_RAIL_Y_NOT_FRONT_POSITION = 453,
        MPC_RIGHT_RAIL_Y_NOT_REAR_POSITION = 454,
        PIPE_PNP_Z_NOT_SAFE_POSITION = 460,
        NEEDLE_PNP_Z_NOT_SAFE_POSITION = 461,
        PIPE_PNP_Y_ON_THE_FEEDER_ZONE = 462,
        NEEDLE_PNP_Y_ON_THE_FEEDER_ZONE = 463,
        PIPE_MOUNT_Z_NOT_SAFE_POSITION = 470,
        NEEDLE_MOUNT_Z_NOT_SAFE_POSITION = 471,
        FLIP_Z_NOT_UP_POSITION = 472,
        DISPENSER_Z_NOT_SAFE_POSITION = 473,

        SEQ00_PIPE_HOLDER_PUSHER_CYLINDER_NOT_UP = 500,
        SEQ00_NEEDLE_HOLDER_PUSHER_CYLINDER_NOT_UP = 501,
        SEQ00_PIPE_FIX_CYLINDER_NOT_UP = 502,
        SEQ00_NEEDLE_FIX_CYLINDER_NOT_UP = 503,
        SEQ00_PIPE_FIX_CYLINDER_NOT_DOWN = 504,
        SEQ00_NEEDLE_FIX_CYLINDER_NOT_DOWN = 505,
        SEQ00_PALLETS_NOT_DETECTION_FRONT_LEFT = 510,
        SEQ00_PALLETS_DETECTION_FRONT_RIGHT = 511,
        SEQ00_PALLETS_PITCH_NOT_DETECTION_FRONT = 512,
        SEQ00_FRONT_MPC_BELT_PITCH_NOT_DETECTION = 513,
        SEQ00_FLIP_CHUCK_OPEN_CYLINDER_TIMEOUT = 520,
        SEQ00_FLIP_CHUCK_CLOSE_CYLINDER_TIMEOUT = 521,
        SEQ00_FLIP_TABLE_LEFT_CYLINDER_TIMEOUT = 522,
        SEQ00_FLIP_TABLE_RIGHT_CYLINDER_TIMEOUT = 523,
        SEQ00_FLIP_TABLE_BWD_CYLINDER_TIMEOUT = 524,
        SEQ00_FLIP_TABLE_FWD_CYLINDER_TIMEOUT = 525,

        //MapData Skip 있으면 다음 공정 시작하기 전에 알람 띄움
        SEQ00_PIPE_SKIPPED_HOLDER_DETECTED = 526,

        SEQ00_NEEDLE_SKIPPED_HOLDER_DETECTED = 527,
        SEQ00_PIPE_NEEDLE_SKIPPED_HOLDER_DETECTED = 528,

        SEQ01_PALLETS_DETECTION_REAR_LEFT = 530,
        SEQ01_PALLETS_DETECTION_FRONT_LEFT = 531,
        SEQ01_PALLETS_NOT_DETECTION_REAR_LEFT = 532,
        SEQ01_PALLETS_NOT_DETECTION_FRONT_LEFT = 533,
        SEQ01_REAR_MPC_BELT_PITCH_NOT_DETECTION = 540,
        SEQ01_FRONT_MPC_BELT_PITCH_NOT_DETECTION = 541,
        SEQ01_LM_RAIL_GUIDE_LEFT_CYLINDER_TIMEOUT = 542,

        SEQ02_PALLETS_DETECTION_REAR_RIGHT = 550,
        SEQ02_PALLETS_DETECTION_FRONT_RIGHT = 551,
        SEQ02_PALLETS_NOT_DETECTION_REAR_RIGHT = 552,
        SEQ02_PALLETS_NOT_DETECTION_FRONT_RIGHT = 553,
        SEQ02_REAR_MPC_BELT_PITCH_NOT_DETECTION = 560,
        SEQ02_FRONT_MPC_BELT_PITCH_NOT_DETECTION = 561,
        SEQ02_LM_RAIL_GRUIDE_RIGHT_CYLINDER_TIMEOUT = 562,
        SEQ02_UV_HOLDER_FIX_CYLINDER_TIMEOUT = 563,

        SEQ03_HOLDER_PICKER_HOLDER_DETECTION = 570,
        SEQ03_HOLDER_PICKER_HOLDER_NOT_DETECTION = 571,
        SEQ03_HOLDER_TRAY_FLOATING_DETECTION = 573,
        SEQ03_HOLDER_PICKER_CHUCK_OPEN_CYLINDER_TIMEOUT = 580,
        SEQ03_HOLDER_PICKER_CHUCK_CLOSE_CYLINDER_TIMEOUT = 581,
        SEQ03_HOLDER_PICKER_CHUCK_UP_CYLINDER_TIMEOUT = 582,
        SEQ03_HOLDER_PICKER_CHUCK_DOWN_CYLINDER_TIMEOUT = 583,
        SEQ03_HOLDER_SUPPLY_TRAY_HOLDER_EMPTY = 584,
        SEQ03_HOLDER_RECOVERY_TRAY_HOLDER_FULL = 585,
        SEQ03_HOLDER_NG_TRAY_HOLDER_FULL = 586,
        SEQ03_MPC_LEFT_RAIL_Y_NOT_SUPPLY_POSITION = 587,

        SEQ04_FEEDER_PIPE_NEEDLE_VISION_TIMEOUT = 590,
        SEQ04_FEEDER_NOT_FIND_PIPE = 591,
        SEQ04_FEEDER_NOT_FIND_NEEDLE = 592,

        SEQ05_PIPE_PnP_VACUUM_DETECTION = 600,
        SEQ05_PIPE_PnP_VACUUM_NOT_DETECTION = 601,
        SEQ05_PIPE_TRANSFER_VACUUM_DETECTION = 602,
        SEQ05_PIPE_TRANSFER_VACUUM_NOT_DETECTION = 603,
        SEQ05_TRANSFER_LEFT_CYLINDER_BWD_TIMEOUT = 610,
        SEQ05_TRANSFER_LEFT_PIPE_DETECTION = 611,
        SEQ05_TRANSFER_LEFT_MOTOR_R_NOT_ORIGIN_POS = 612,
        SEQ05_PIPE_PNP_VISION_TIMEOUT = 613,
        SEQ05_PIPE_PNP_CALIBRATION_JIG_FIND_FAIL = 614,

        SEQ06_NEEDLE_PnP_VACUUM_DETECTION = 620,
        SEQ06_NEEDLE_PnP_VACUUM_NOT_DETECTION = 621,
        SEQ06_NEEDLE_TRANSFER_VACUUM_DETECTION = 622,
        SEQ06_NEEDLE_TRANSFER_VACUUM_NOT_DETECTION = 623,
        SEQ06_TRANSFER_RIGHT_CYLINDER_BWD_TIMEOUT = 630,
        SEQ06_TRANSFER_RIGHT_NEEDLE_DETECTION = 631,
        SEQ06_TRANSFER_RIGHT_MOTOR_R_NOT_ORIGIN_POS = 632,
        SEQ06_NEEDLE_PNP_VISION_TIMEOUT = 633,
        SEQ06_NEEDLE_PNP_CALIBRATION_JIG_FIND_FAIL = 634,

        SEQ07_TRANSFER_LEFT_CYLINDER_BWD_TIMEOUT = 640,
        SEQ07_TRANSFER_LEFT_CYLINDER_FWD_TIMEOUT = 641,
        SEQ07_TRANSFER_LEFT_TRIGGER_FWD_SENSOR_DETECTION = 642,
        SEQ07_TRANSFER_LEFT_TRIGGER_FWD_SENSOR_NOT_DETECTION = 643,
        SEQ07_TRANSFER_LEFT_PIPE_DETECTION = 644,
        SEQ07_TRANSFER_LEFT_PIPE_NOT_DETECTION = 645,
        SEQ07_TRANSFER_LEFT_VISION_TIMEOUT = 646,
        SEQ07_TRANSFER_RIGHT_CYLINDER_BWD_TIMEOUT = 650,
        SEQ07_TRANSFER_RIGHT_CYLINDER_FWD_TIMEOUT = 651,
        SEQ07_TRANSFER_RIGHT_TRIGGER_FWD_SENSOR_DETECTION = 652,
        SEQ07_TRANSFER_RIGHT_TRIGGER_FWD_SENSOR_NOT_DETECTION = 653,
        SEQ07_TRANSFER_RIGHT_NEEDLE_DETECTION = 654,
        SEQ07_TRANSFER_RIGHT_NEEDLE_NOT_DETECTION = 655,
        SEQ07_TRANSFER_RIGHT_VISION_TIMEOUT = 656,

        SEQ08_PIPE_MOUNT_CHUCK_CYLINDER_OPEN_TIMEOUT = 660,
        SEQ08_PIPE_MOUNT_CHUCK_CYLINDER_CLOSE_TIMEOUT = 661,
        SEQ08_HOLDER_FIX_CYLINDER_DOWN_TIMEOUT = 662,
        SEQ08_HOLDER_PIPE_PUSHER_CYLINDER_DOWN_TIMEOUT = 663,
        SEQ08_HOLDER_PIPE_PUSHER_CYLINDER_UP_TIMEOUT = 664,
        SEQ08_TRANSFER_LEFT_PIPE_NOT_DETECTION = 670,
        SEQ08_TRANSFER_LEFT_CYLINDER_FWD_TIMEOUT = 671,
        SEQ08_TRANSFER_LEFT_MOTOR_R_NOT_POSTURE_POS = 672,
        SEQ08_PIPE_MOUNT_VISION_TIMEOUT = 673,
        SEQ08_PIPE_MOUNT_NOT_FIND_HOLE = 674,
        SEQ08_PIPE_MOUNT_HOLDER_EMPTY = 675,

        SEQ09_NEEDLE_MOUNT_CHUCK_CYLINDER_OPEN_TIMEOUT = 680,
        SEQ09_NEEDLE_MOUNT_CHUCK_CYLINDER_CLOSE_TIMEOUT = 681,
        SEQ09_HOLDER_FIX_CYLINDER_DOWN_TIMEOUT = 682,
        SEQ09_HOLDER_NEEDLE_PUSHER_CYLINDER_DOWN_TIMEOUT = 683,
        SEQ09_HOLDER_NEEDLE_PUSHER_CYLINDER_UP_TIMEOUT = 684,
        SEQ09_TRANSFER_RIGHT_NEEDLE_NOT_DETECTION = 690,
        SEQ09_TRANSFER_RIGHT_CYLINDER_FWD_TIMEOUT = 691,
        SEQ09_TRANSFER_RIGHT_MOTOR_R_NOT_POSTURE_POS = 692,
        SEQ09_NEEDLE_MOUNT_VISION_TIMEOUT = 693,
        SEQ09_NEEDLE_MOUNT_NOT_FIND_HOLE = 694,
        SEQ09_NEEDLE_MOUNT_HOLDER_EMPTY = 695,

        SEQ10_DISP_HEIGH_CHECK_CYLINDER_UP_TIMEOUT = 700,
        SEQ10_DISP_HEIGH_CHECK_CYLINDER_DOWN_TIMEOUT = 701,
        SEQ10_DISP_NOZZLE_HEIGH_SENSOR_NOT_DETECTION = 702,
        SEQ10_DISP_VISION_TIMEOUT = 710,
        SDQ10_DISP_LIQUIDE_RELOAD = 711,
        SEQ10_DISP_CHANGE_CLEAN_PAPER = 712,
        SEQ10_DISP_HOLDER_EMPTY = 713,
        SEQ10_DISP_HOLDER_POSITION_FAIL = 714,
        SEQ10_DISP_PIPEorNEEDLE_EMPTY = 715,
        SEQ10_DISP_NEEDLE_EMPTY = 716,

        PIPE_1_INSERTION_FAIL = 1000,
        PIPE_2_INSERTION_FAIL = 1001,
        PIPE_3_INSERTION_FAIL = 1002,
        PIPE_4_INSERTION_FAIL = 1003,
        PIPE_5_INSERTION_FAIL = 1004,
        PIPE_6_INSERTION_FAIL = 1005,
        PIPE_7_INSERTION_FAIL = 1006,
        PIPE_8_INSERTION_FAIL = 1007,
        PIPE_9_INSERTION_FAIL = 1008,
        PIPE_10_INSERTION_FAIL = 1009,
        PIPE_11_INSERTION_FAIL = 1010,
        PIPE_12_INSERTION_FAIL = 1011,
        PIPE_13_INSERTION_FAIL = 1012,
        PIPE_14_INSERTION_FAIL = 1013,
        PIPE_15_INSERTION_FAIL = 1014,
        PIPE_16_INSERTION_FAIL = 1015,
        PIPE_17_INSERTION_FAIL = 1016,
        PIPE_18_INSERTION_FAIL = 1017,
        PIPE_19_INSERTION_FAIL = 1018,

        NEEDLE_1_INSERTION_FAIL = 1020,
        NEEDLE_2_INSERTION_FAIL = 1021,
        NEEDLE_3_INSERTION_FAIL = 1022,
        NEEDLE_4_INSERTION_FAIL = 1023,
        NEEDLE_5_INSERTION_FAIL = 1024,
        NEEDLE_6_INSERTION_FAIL = 1025,
        NEEDLE_7_INSERTION_FAIL = 1026,
        NEEDLE_8_INSERTION_FAIL = 1027,
        NEEDLE_9_INSERTION_FAIL = 1028,
        NEEDLE_10_INSERTION_FAIL = 1029,
        NEEDLE_11_INSERTION_FAIL = 1030,
        NEEDLE_12_INSERTION_FAIL = 1031,
        NEEDLE_13_INSERTION_FAIL = 1032,
        NEEDLE_14_INSERTION_FAIL = 1033,
        NEEDLE_15_INSERTION_FAIL = 1034,
        NEEDLE_16_INSERTION_FAIL = 1035,
        NEEDLE_17_INSERTION_FAIL = 1036,
        NEEDLE_18_INSERTION_FAIL = 1037,
        NEEDLE_19_INSERTION_FAIL = 1038,

        UNKNOWN_ALARM = 9999,
    }

    /// <summary>
    /// 알람 번호 정의
    /// </summary>
    public enum eAlarmCode
    {
        UNKNOWN_ALARM = 9999,
    }
}