namespace MachineControlBase
{
    /// <summary>
    /// Input Address Define
    /// </summary>
    public enum eIO_I : int
    {
        /* MAIN */
        MOTOR_POWER_MC1_ON = 0,
        CONTROL_POWER_MC2_ON = 1,
        MAIN_AIR = 2,
        EMERGENCY_SW_1_OFF_FRONT_RIGHT = 3,
        EMERGENCY_SW_2_OFF_REAR = 4,
        SAFETY_PLC_ALARM = 5,
        INTERLOCK_BY_PASS_ON_SOFTWERE = 10,
        INTERLOCK_BY_PASS_OFF_SOFTWERE = 11,

        /* DOOR */
        DOOR_SWITCH_1_CLOSE_CHECK_DOOR_CLOSE_ON_FRONT_RIGHT = 14,
        DOOR_SOLENOID_1_LOCK_CHECK_DOOR_LOCK_ON_FRONT_RIGHT = 15,
        DOOR_SWITCH_2_CLOSE_CHECK_DOOR_LOCK_ON_FRONT_CENTER_RIGHT = 16,
        DOOR_SOLENOID_2_LOCK_CHECK_DOOR_LOCK_ON_FRONT_CENTER_RIGHT = 17,
        DOOR_SWITCH_3_CLOSE_CHECK_DOOR_CLOSE_ON_FRONT_CENTER_LEFT = 18,
        DOOR_SOLENOID_3_LOCK_CHECK_DOOR_LOCK_ON_FRONT_CENTER_LEFT = 19,
        DOOR_SWITCH_4_CLOSE_CHECK_DOOR_CLOSE_ON_REAR_LEFT = 20,
        DOOR_SOLENOID_4_LOCK_CHECK_DOOR_LOCK_ON_REAR_LEFT = 21,
        DOOR_SWITCH_5_CLOSE_CHECK_DOOR_CLOSE_ON_REAR_RIGHT = 22,
        DOOR_SOLENOID_5_LOCK_CHECK_DOOR_LOCK_ON_REAR_RIGHT = 23,

        /* IONIZER */
        IONIZER_MAINTENANCE = 24,
        IONIZER_ERROR = 25,

        /* FLIP 테이블 전 후진 */
        FLIP_TABLE_BWD = 28,
        FLIP_TABLE_FWD = 29,

        /* PIPE & NIDDLE VACUUM */
        PNP_PIPE_VACUUM = 32,
        PNP_NEEDLE_VACUUM = 33,
        TRANSFER_PIPE_TRIGGER = 34,
        TRANSFER_NEEDLE_TRIGGER = 35,
        TRANSFER_PIPE_VACUUM = 36,
        TRANSFER_NEEDLE_VACUUM = 37,

        /* TRANSFER */
        TRANSFER_PIPE_FORWARD = 38,
        TRANSFER_PIPE_BACKWARD_ON = 39,
        TRANSFER_NEEDLE_FORWARD = 40,
        TRANSFER_NEEDLE_BACKWARD_ON = 41,

        /* PIPE MOUNT */
        PIPE_CHUCK_CLOSE_ON = 42,
        PIPE_CHUCK_OPEN = 43,
        PIPE_PUSHER_UP_ON = 44,
        PIPE_PUSHER_DOWN = 45,
        PIPE_HOLDER_FIXTURE_UP_ON = 46,
        PIPE_HOLDER_FIXTURE_DOWN = 47,

        /* NIDDLE MOUNT */
        NEEDLE_CHUCK_CLOSE_ON = 48,
        NEEDLE_CHUCK_OPEN = 49,
        NEEDLE_PUSHER_UP_ON = 50,
        NEEDLE_PUSHER_DOWN = 51,
        NEEDLE_HOLDER_FIXTURE_UP_ON = 52,
        NEEDLE_HOLDER_FIXTURE_DOWN = 53,

        /* FLIP */
        FLIP_CHUCK_CLOSE = 54,
        FLIP_CHUCK_OPEN_ON = 55,
        FLIP_TABLE_LEFT = 56,
        FLIP_TABLE_RIGHT_ON = 57,

        /* DISPENSER */
        DISP_NOZZLE_HEIGHT_CHECK_SENSOR = 58,

        /* MPC */
        BELT_PITCH_DETECTION_LEFT = 60,
        BELT_PITCH_DETECTION_RIGHT = 61,
        PALLETS_PITCH_DETECTION_FRONT = 62,
        PALLETS_DETECTION_FRONT_LEFT = 64,
        PALLETS_DETECTION_FRONT_RIGHT = 65,
        PALLETS_DETECTION_REAR_LEFT = 66,
        PALLETS_DETECTION_REAR_RIGHT = 67,
        LM_RAIL_FORWARD_LEFT = 68,
        LM_RAIL_FORWARD_ON_LEFT = 69,
        LM_RAIL_FORWARD_RIGHT = 70,
        LM_RAIL_FORWARD_ON_RIGHT = 71,

        /* UV */
        HOLDER_FIXTURE_UP_ON = 72,
        HOLDER_FIXTURE_DOWN = 73,

        /* DISP NOZZLE HEIGHT CHECK */
        DISP_NEEDLE_FLAT_CHECK_UP_ON = 74,
        DISP_NEEDLE_FLAT_CHECK_DOWN = 75,

        /* HOLDER LOADING */
        HOLDER_FLOATING_DETECTION = 80,
        HOLDER_CHUCK_UP_ON = 81,
        HOLDER_CHUCK_DOWN = 82,
        HOLDER_CHUCK_CLOSE_ON = 83,
        HOLDER_CHUCK_OPEN = 84,
        HOLDER_DETECTION = 85,

        /* MAIN EMO & INTERLOCK KEY */
        EMERGENCY_SW_3_OFF_FRONT_LEFT = 87,
        DOOR_SWITCH_6_CLOSE_CHECK_DOOR_CLOSE_ON_FRONT_LEFT = 88,
        DOOR_SOLENOID_6_LOCK_CHECK_DOOR_LOCK_ON_FRONT_LEFT = 89,
    }

    /// <summary>
    /// Output Address Define
    /// </summary>
    public enum eIO_O : int
    {
        /* MAIN POWER */
        CONTROL_POWER_ON = 1,
        SOFTREWE_BY_PASS_ON_OFF = 2,

        /* 파이프 홀더 전자석 */
        PIPE_HOLDER_ELECTROMAGNET = 7,

        /* TOWER LAMP */
        TOWER_LAMP_RED = 8,
        TOWER_LAMP_YELLOW = 9,
        TOWER_LAMP_GREEN = 10,
        TOWER_LAMP_BUZZER = 11,

        /* IONIZER */
        IONIZER_ONOFF = 12,

        /* HEPA FILTER */
        HEPA_FILTER_ONOFF = 13,

        /* 형광등 */
        FLUORESCENT_LAMP_ONOFF = 14,

        /* DOOR SOL LOCK */
        DOOR_SOLENOID_LOCK_ONOFF = 15,

        /* PIPE NIDDLE P&P */
        PIPE_VACUUM = 16,
        PIPE_BLOW = 17,
        NEEDLE_VACUUM = 18,
        NEEDLE_BLOW = 19,

        /* TRANSFER */
        TRANSFER_PIPE_VACUUM = 20,
        TRANSFER_PIPE_BLOW = 21,
        TRANSFER_NEEDLE_VACUUM = 22,
        TRANSFER_NEEDLE_BLOW = 23,
        TRANSFER_PIPE_FORWARD = 24,
        TRANSFER_PIPE_BACKWARD = 25,
        TRANSFER_NEEDLE_FORWARD = 26,
        TRANSFER_NEEDLE_BACKWARD = 27,

        /* PIPE MOUNT */
        PIPE_CHUCK_OPEN = 28,
        PIPE_PUSHER_DOWN = 29,
        FIXTURE_DOWN = 30,

        /* NIDDLE MOUNT */
        DISPENSER_CLEAN_BLOW = 31,
        NEEDLE_CHUCK_OPEN = 32,
        NEEDLE_PUSHER_DOWN = 33,
        HOPPER_NEEDLE_BLOW = 34,

        /* FLIP */
        FLIP_CHUCK_OPEN = 35,
        FLIP_CHUCK_CLOSE = 36,
        FLIP_TABLE_LEFT = 37,
        FLIP_TABLE_RIGHT = 38,

        /* DISPENSER */
        DISPENSER_VALVE_OPEN = 39,

        /* MPC */
        PARTICLE_SUCTION = 40,
        LM_RAIL_FORWARD_LEFT = 42,
        LM_RAIL_FORWARD_RIGHT = 43,

        /* UV */
        UV_FIXTURE_DOWN = 44,

        /* NEEDLE 클램프 블로우 */
        NEEDLE_CLAMP_BLOW = 45,

        /* DISP NOZZLE HEIGH CHECK */
        DISP_NEEDLE_FLAT_DOWN = 46,

        /* NEEDLE 클램프 진공 */
        NEEDLE_CLAMP_VACUUM = 47,

        /* HOLDER LOADING */
        HOLDER_CHUCK_DOWN = 48,
        HOLDER_CHUCK_OPEN = 49,

        /* Flip 테이블 전 후진 */
        FLIP_TABLE_FWD_BWD = 50,
    }
}